README.md

Fix spelling, indentation and remove trailing spaces

---

README.md
examples/migrations/20170119011451314_test_migration.cr
generate-docs.sh
shard.yml
spec/adapter/mysql_spec.cr
spec/adapter/postgres_spec.cr
spec/model/mapping_spec.cr
spec/models.cr
spec/query_builder/condition_spec.cr
spec/spec_helper.cr
src/jennifer/adapter/base.cr
src/jennifer/adapter/postgres.cr
src/jennifer/adapter/postgres/condition.cr
src/jennifer/adapter/postgres/criteria.cr
src/jennifer/query_builder/model_query.cr
src/jennifer/version.cr

requested [by](https://github.com/imdrasil/jennifer.cr/issues/12).
Markdown still improperly parses tables.

add pg array support and doc generating

---

README.md

add require sam to sam.cr

---

examples/migrations/20170815112803321_model_with_one_field.cr
spec/adapter/base_spec.cr
spec/factories.cr
spec/model/base_spec.cr
spec/model/callback_spec.cr
spec/model/mapping_spec.cr
spec/model/relation_definition_spec.cr
spec/model/validation_spec.cr
spec/models.cr
spec/query_builder/condition_spec.cr
spec/query_builder/criteria_spec.cr
spec/query_builder/expression_builder_spec.cr
spec/query_builder/join_spec.cr
spec/query_builder/query_spec.cr
spec/spec_helper.cr
src/jennifer/adapter/base_sql_generator.cr
src/jennifer/adapter/mysql/sql_notation.cr
src/jennifer/adapter/postgres/sql_notation.cr
src/jennifer/migration/runner.cr
src/jennifer/model/base.cr
src/jennifer/model/mapping.cr
src/jennifer/query_builder/join.cr

Adds factory usage and solve problem of models with only field(fix for [this issue](https://github.com/imdrasil/jennifer.cr/issues/19) )

Fix one field issue

---

examples/migrations/20170912145453751_add_index.cr
spec/factories.cr
spec/model/base_spec.cr
spec/query_builder/model_query_spec.cr
spec/spec_helper.cr
src/jennifer/adapter/base.cr
src/jennifer/adapter/postgres.cr
src/jennifer/adapter/postgres/sql_notation.cr
src/jennifer/migration/version.cr
src/jennifer/model/base.cr
src/jennifer/model/mapping.cr

[Original Issue](https://github.com/imdrasil/jennifer.cr/issues/35)
Use old variant of id retrieving for inserted record. This invokes extra request but for current state of pg driver is the only solution

Switched to old method of returning id for inserted object

---

spec/model/mapping_spec.cr
src/jennifer/adapter/base.cr
src/jennifer/adapter/mysql.cr
src/jennifer/adapter/postgres.cr
src/jennifer/adapter/result_parsers.cr
src/jennifer/adapter/sqlite3.cr
src/jennifer/exceptions.cr
src/jennifer/query_builder/query.cr

Added query information to exceptions raised during building model object

Improve model building error messages

---

README.md
docs/query_dsl.md
spec/adapter/base_spec.cr
spec/model/mapping_spec.cr
spec/query_builder/model_query_spec.cr
src/jennifer/query_builder/model_query.cr

Switch #includes and #preload behaviors; rename new #preload to #eager_load. This makes Jennifer behavior slightly more similar to rails 5 ActiveRecord

Change #includes method behvior

---

spec/model/mapping_spec.cr
src/jennifer/exceptions.cr
src/jennifer/model/mapping.cr

Updates the RecordInvalid exception to take the validation error list containing each of the failing validations

raise exception with error list when model validation fails

---

src/jennifer/adapter/base_sql_generator.cr

I'm seeing strange 'no target def' compiler issues during sql generation for migrations for a number of the different clauses. e.g.
```bash
DB=mysql crystal db/run.cr -- db:setup                                                                                                                                     130 ↵
Error in lib/jennifer/src/jennifer/adapter/base_sql_generator.cr:116: BUG: no target defs
query._unions!.each do |u|
^~~~
```
Interestingly it doesn't happen in the test migrations for the project, but this repo illustrates the issue. https://github.com/sgargan/migration-issue
I've made changes to the base_sql_generator that makes the compiler happy and allows it to run.

fix no target defs issue during migration

---

docs/aggregation.md

Adds missing title to doc

---

spec/model/base_spec.cr
src/jennifer/adapter/base.cr
src/jennifer/adapter/base_sql_generator.cr
src/jennifer/adapter/mysql.cr
src/jennifer/adapter/postgres.cr
src/jennifer/adapter/request_methods.cr
src/jennifer/exceptions.cr
src/jennifer/model/base.cr
src/jennifer/model/mapping.cr

- add bulk insert to adapters
- add bulk insert to model class
- add table lock (postgres only)

Add multiobject insert

---

spec/model/relation_definition_spec.cr
spec/models.cr
spec/query_builder/model_query_spec.cr
src/jennifer/model/base.cr
src/jennifer/model/relation_definition.cr
src/jennifer/view/base.cr

- add `inverse_of` option to `has_many` and `has_one` relations

Add inverse_of option to relation definition

---

spec/model/base_spec.cr
src/jennifer/model/base.cr
src/jennifer/model/mapping.cr

Fixing default build method on the model without default constructor (fix for #73 )

Move default build method to Mapping module

---

docs/validation.md
spec/model/validation_spec.cr
spec/models.cr
src/jennifer/model/validation.cr

#76 
Now `presence_of` validation could be added to model and view to validate presence of value (if it is not `nil`).

Add presence_of validation

---

docs/model_mapping.md
spec/model/callback_spec.cr
spec/models.cr
src/jennifer/model/callback.cr

- Show availability to inherit model from "`ApplicationRecord`" class
- Fix inherited callbacks invocation

Fix model class inheritance and callbacks invocation

---

spec/query_builder/executables_spec.cr
spec/query_builder/joining_spec.cr
spec/query_builder/model_query_spec.cr
spec/query_builder/ordering_spec.cr
spec/query_builder/query_spec.cr
src/jennifer/query_builder/aggregations.cr
src/jennifer/query_builder/executables.cr
src/jennifer/query_builder/model_query.cr
src/jennifer/query_builder/ordering.cr

- add `#find_each` method to `Query` and `ModelQuery`
- refactor tests
- refactor `#find_in_batches` - arguments order is changed

Add #find_each method

---

CHANGELOG.md
shard.yml
src/jennifer/version.cr

bump version

---

CHANGELOG.md
README.md
docs/record.md
docs/view.md
spec/fixtures/only_sam.cr
spec/model/mapping_spec.cr
spec/models.cr
src/jennifer.cr
src/jennifer/adapter/postgres/sql_notation.cr
src/jennifer/exceptions.cr
src/jennifer/migration/version.cr
src/jennifer/model/base.cr
src/jennifer/model/scoping.cr
src/jennifer/query_builder/i_model_query.cr
src/jennifer/query_builder/query.cr

- make IModelQuery#model_class pseudo abstract (fix #89 )
- update docs
- add new exception - `AbsractMethod`

Make IModelQuery#model_class pseudo abstract

---

docs/_config.yml
docs/model_mapping.md
docs/view.md
spec/adapter/record_spec.cr
spec/model/base_spec.cr
spec/model/mapping_spec.cr
spec/models.cr
spec/view/base_spec.cr
spec/view/experimental_mapping_spec.cr
src/jennifer.cr
src/jennifer/macros.cr
src/jennifer/model/base.cr
src/jennifer/model/mapping.cr
src/jennifer/view/base.cr
src/jennifer/view/experimental_mapping.cr

- added columns metadata (#31)
- added some pending tests
- removed `FIELD_NAMES` model constant

Added columns metadata

---

CHANGELOG.md
README.md
docs/query_dsl.md
shard.yml
src/jennifer/version.cr

Update changelog and readme before 0.4.3 release

Bump to 0.4.3

---

.travis.setup.sh
.travis.yml
docs/configuration.md
spec/adapter/base_spec.cr
spec/config.cr
src/jennifer/adapter/base.cr
src/jennifer/adapter/postgres.cr
src/jennifer/adapter/postgres/legacy_insert.cr
src/jennifer/adapter/postgres/sql_generator.cr

- switch postgres to use `RETURNING` instead of quering `currval` after inserting
- add `jennifer/adapter/postgres/legacy_insert` file to allow switching to old inserting method

Switch postgres to use returning statement

---

docs/configuration.md
docs/model_mapping.md
docs/timestamps.md
shard.yml
spec/adapter/base_spec.cr
spec/adapter/mysql_spec.cr
spec/adapter/postgres_spec.cr
spec/adapter/sql_generator_spec.cr
spec/factories.cr
spec/model/mapping_spec.cr
spec/models.cr
spec/spec_helper.cr
spec/view/experimental_mapping_spec.cr
src/jennifer.cr
src/jennifer/adapter/base.cr
src/jennifer/adapter/base_sql_generator.cr
src/jennifer/adapter/postgres.cr
src/jennifer/adapter/postgres/legacy_insert.cr
src/jennifer/adapter/postgres/sql_generator.cr
src/jennifer/adapter/request_methods.cr
src/jennifer/adapter/schema_processor.cr
src/jennifer/config.cr
src/jennifer/model/mapping.cr
src/jennifer/query_builder/i_model_query.cr
src/jennifer/view/experimental_mapping.cr

- automatically converts time from local time to utc during saving to the db and back during reading
- automatically converts time to utc in query arguments
- minor optimizations

Add time zone

---

docs/model_mapping.md
spec/model/mapping_spec.cr
spec/model/sti_mapping_spec.cr
spec/model/validation_spec.cr
spec/models.cr
src/jennifer/model/mapping.cr
src/jennifer/model/sti_mapping.cr

- adds virtual attributes - they are accessible during mass assignment but not stored to db

Add virtual attributes

---

spec/adapter/base_spec.cr
spec/model/mapping_spec.cr
spec/model/parameter_converter_spec.cr
src/jennifer/adapter/base.cr
src/jennifer/adapter/postgres/numeric.cr
src/jennifer/adapter/shared/types.cr
src/jennifer/config.cr
src/jennifer/model/base.cr
src/jennifer/model/mapping.cr
src/jennifer/model/parameter_converter.cr

- fixes `PG::Numeric` initialization for non pg apps
- fixes `Jennifer::Model::Base::build_params` - allows nillable values
- fixes building db connection string with specified port

fix pg numeric

---

docs/model_mapping.md
spec/model/base_spec.cr
src/jennifer/model/base.cr
src/jennifer/model/relation_definition.cr
src/jennifer/model/sti_mapping.cr
src/jennifer/relation/base.cr
src/jennifer/relation/belongs_to.cr

- removes `::singular_table_name` method
- adds `::table_prefix` optional method

Add table_prefix

---

README.md
docs/configuration.md
spec/adapter/base_spec.cr
spec/config.cr
spec/spec_helper.cr
src/jennifer/adapter/base.cr
src/jennifer/config.cr

- Fix invalid adding of  database port to connection string (#121)

Fix invalid db port adding to connection string

---

src/jennifer/query_builder/criteria_container.cr

Fix compile time issue with order direction type mismatch

---

docs/query_dsl.md
spec/adapter/sql_generator_spec.cr
spec/query_builder/condition_spec.cr
src/jennifer/query_builder/condition.cr
src/jennifer/query_builder/query.cr

- add lhs sql arguments to be processed during query generating (#123 )
- tiny documentation enhancement

fix condition lhs processing

---

docs/model_mapping.md
spec/model/mapping_spec.cr
spec/models.cr
spec/spec_helper.cr
src/jennifer/adapter/base.cr
src/jennifer/adapter/postgres.cr
src/jennifer/model/base.cr
src/jennifer/model/mapping.cr
src/jennifer/model/sti_mapping.cr

- allows defining non `PG::Numeric` type for postgre numeric field (fix  for #128 )

Add  PG::Numeric converter

---

examples/migrations/20170815112803321_add_model_with_one_field.cr
examples/run.cr
spec/model/relation_definition_spec.cr
spec/models.cr
src/jennifer/adapter/base.cr
src/jennifer/adapter/postgres.cr
src/jennifer/adapter/postgres/schema_processor.cr
src/jennifer/model/base.cr
src/jennifer/model/mapping.cr

- allows defining primary field as `BIGINT`
- fix initializing `Int64` primary field

Allows to defined int64 primary field

---

spec/model/base_spec.cr
spec/view/base_spec.cr
src/jennifer/model/resource.cr

- add resource inspect with only columns information

Add resource inspect

---

spec/model/mapping_spec.cr
src/jennifer/model/mapping.cr

- allow building model with specified numeric converter field using defined field type and numeric one

Enhancement postgres numeric field - hash contructor 

---

spec/config.cr
src/jennifer/model/callback.cr
src/jennifer/model/relation_definition.cr

Replaces some nested macros definition with `verbatim` crystal 0.25.0 feature.
This increases readability.

Replace some nested macro with verbatim

---

CHANGELOG.md
README.md
shard.yml
src/jennifer.cr
src/jennifer/adapter/shared/types.cr
src/jennifer/model/base.cr
src/jennifer/model/translation.cr
src/jennifer/query_builder.cr
src/jennifer/query_builder/condition.cr
src/jennifer/query_builder/json_selector.cr
src/jennifer/query_builder/logic_operator.cr
src/jennifer/relation/relation_stub.cr
src/jennifer/validator.cr
src/jennifer/version.cr

Bump next patch release and adds some small project restructuring

0.6.1 release

---

CHANGELOG.md
README.md
shard.yml
src/jennifer.cr
src/jennifer/version.cr

0.6.2 Release

---

src/jennifer/model/mapping.cr
src/jennifer/model/sti_mapping.cr
src/jennifer/view/experimental_mapping.cr

Mapping macro clean-up

---

README.md

While reading the README of the project, I noticed that some links in "Similar shards" section are not correct. I hope you don't mind me correcting them. (It also contains some wording improvement suggestions)

Fix links to similar shards

---

spec/integration/concurrency_test.cr
spec/query_builder/query_spec.cr
src/jennifer/adapter/transactions.cr

Ensure current connection to be released even if it has got an exception
**Adapter**
* `Transaction#with_connection` ensure to release connection

ensure current connection to be released even if it has got an exception

---

docs/authentication.md
docs/crud.md
docs/migration.md
docs/record.md
docs/relations.md
docs/view.md
src/jennifer/adapter/record.cr

Fixes doc typos (including #213)

Fix documentation typos

---

spec/query_builder/query_spec.cr
src/jennifer/query_builder/query.cr

Adds `Jennifer::Query#merge`
* add `Query#merge`

Add #merge query method

---

spec/adapter/base_sql_generator_spec.cr
spec/query_builder/cast_spec.cr
src/jennifer/adapter/base_sql_generator.cr
src/jennifer/query_builder/cast.cr
src/jennifer/query_builder/expression_builder.cr

Adds sql `CAST`.
* add `ExpressionBuilder#cast`

Add `CAST` sql method

---

src/jennifer/query_builder/executables.cr

Fix missing `LIMIT` in `Executables#first!`
* fix missing `LIMIT` in query generated by `#first!`

Add missing LIMIT to #first!

---

shard.yml
src/jennifer/model/authentication.cr

Replace `Crypto::Bcrypt::Password#==` by `Crypto::Bcrypt::Password#verify`

Upgrade to crystal 0.29

---

CHANGELOG.md
README.md
docs/getting_started.md
shard.yml
src/jennifer.cr

Bump 0.8.1

---

CHANGELOG.md
README.md
docs/getting_started.md
shard.yml
src/jennifer.cr

Fix #265.
**General**
* upgrade i18n dependency

Upgrade I18n dependency

---

.travis.yml
docs/command_line.md
docs/getting_started.md
shard.yml
spec/integration/sam_test.cr
spec/integration/shared_helpers.cr
spec/integration/spec_helper.cr
spec/migration/runnser_spec.cr
spec/support/matchers.cr
src/jennifer/adapter/request_methods.cr
src/jennifer/adapter/transactions.cr
src/jennifer/migration/runner.cr

**General**
* remove `sam` from mandatory dependencies
**Migration**
* add `Runner.pending_migration?` to return whether there is pending (not invoked) migration

Make small migration enhancements; remove sam from dependencies

---

src/jennifer/adapter/schema_processor.cr
src/jennifer/migration/table_builder/create_foreign_key.cr
src/jennifer/migration/table_builder/create_table.cr

**Migration**
* Add foreign key ON UPDATE and ON DELETE support.

Add foreign key ON UPDATE and ON DELETE support.

---

examples/migrations/20170916095004544_add_view.cr
spec/adapter/base_spec.cr
spec/query_builder/ordering_spec.cr
src/jennifer/adapter.cr
src/jennifer/adapter/base_sql_generator.cr
src/jennifer/adapter/postgres/schema_processor.cr
src/jennifer/adapter/schema_processor.cr
src/jennifer/config.cr
src/jennifer/exceptions.cr
src/jennifer/migration/runner.cr
src/jennifer/migration/table_builder/base.cr
src/jennifer/model/field_declaration.cr
src/jennifer/model/mapping.cr
src/jennifer/model/relation_definition.cr
src/jennifer/model/sti_mapping.cr
src/jennifer/query_builder/common_table_expression.cr
src/jennifer/query_builder/criteria.cr
src/jennifer/query_builder/ordering.cr
src/jennifer/relation/base.cr
src/jennifer/validations/acceptance.cr
src/jennifer/validations/confirmation.cr
src/jennifer/view/mapping.cr

* fix `Ordering#order(Hash(String | Symbol, String | Symbol))`
**Adapter**
* add `SchemaProcessor::FkEventActions` enum to validate `on_delete` and `on_update` action values; `String | Symbol` still should be used as an argument type everywhere
**Config**
* add `MigrationFailureHandler` enum to validate `migration_failure_handler_method` value; `Symbol | MigrationFailureHandler` should be used as an argument for it
* fix `migration_failure_handler_method` config - make it instance property

General code clean up

---

docs/getting_started.md

Fix docs typo and not obvious steps in getting started

---

spec/adapter/command_shell/bash_spec.cr
spec/adapter/command_shell/docker_spec.cr
spec/adapter/command_shell/spec_helper.cr
spec/adapter/postgres/command_interface_spec.cr
spec/spec_helper.cr
spec/support/matchers.cr
src/jennifer/adapter/command_shell/bash.cr
src/jennifer/adapter/command_shell/docker.cr
src/jennifer/adapter/command_shell/i_command_shell.cr
src/jennifer/adapter/postgres/command_interface.cr

Fix #301
**Adapter**
* respect host in `Jennifer::Postgres::CommandInterface#database_exists?`

Fix checking whether database exists

---

shard.yml
spec/adapter/base_spec.cr
src/jennifer/adapter/base.cr

**Adapter**
* escape connection URI segments

Escape all segments of connection urls

---

docs/multiple_adapters.md
examples/run.cr
spec/query_builder/executables_spec.cr
spec/query_builder/model_query_spec.cr
src/jennifer/adapter/request_methods.cr
src/jennifer/migration/base.cr
src/jennifer/model/base.cr
src/jennifer/model/mapping.cr
src/jennifer/model/resource.cr
src/jennifer/query_builder/executables.cr
src/jennifer/query_builder/i_model_query.cr
src/jennifer/query_builder/model_query.cr

Improve multi-adapter support
**Model**
* add read/write adapter segregation

Add opportunity to override only read or write adapter

---

README.md
shard.yml
spec/adapter/base_spec.cr
spec/config.cr
spec/integration/concurrency_test.cr
spec/integration/spec_helper.cr
spec/spec_helper.cr
src/jennifer/adapter/base.cr
src/jennifer/adapter/base_sql_generator.cr
src/jennifer/adapter/mysql/sql_generator.cr
src/jennifer/adapter/postgres/sql_generator.cr
src/jennifer/exceptions.cr
src/jennifer/migration/table_builder/create_foreign_key.cr
src/jennifer/model/resource.cr

Add Crystal 0.35.0 support (thanks to @gaku-sei for assist)
**General**
* add crystal 0.35.0 support and drop 0.34.0 support

Add crystal 0.35 support

---

shard.yml
src/jennifer/validations/length.cr
src/jennifer/validations/macros.cr

fix error cannot use 'in' as an argument name

---

.github/workflows/ci.yml
.github/workflows/docs.yml
shard.yml

- add nightly crystal version check
- add automatic docs compilation

Add nightly crystal version

---

CHANGELOG.md
README.md
docs/getting_started.md
shard.yml
src/jennifer.cr

Bump 0.11.0

---

shard.yml

Updates the shards file to use the latest 0.4.1 version of the i18n.cr shard

Updated the i18n.cr shard details to use the latest version

---

docs/transaction_and_lock.md

Add optimistic locking to docs
Please fill the corresponding section regarding this pull request notes below instead of modifying `CHANGELOG.md` file. Please remove all redundant sections before posting request.
**General**
Add optimistic locking section to transaction_and_lock.md

Add optimistic locking section to transaction and lock doc

---

.github/run_integration_tests.sh
.github/shard_1_3_2.yml
docs/getting_started.md
docs/migration.md
scripts/micrate.cr
scripts/migrations/20200315234811_create_contacts.sql
shard.override.yml
shard.yml
spec/adapter/postgres/sql_generator_spec.cr
spec/adapter/result_parsers_spec.cr
spec/config.cr
spec/integration/concurrency_test.cr
spec/integration/micrate_test.cr
spec/integration/sam/blank_application.cr
spec/integration/sam_test.cr
spec/integration/shared_helpers.cr
spec/integration/spec_helper.cr
spec/query_builder/executables_spec.cr
src/jennifer/adapter.cr
src/jennifer/adapter/quoting.cr
src/jennifer/adapter/shared/types.cr
src/jennifer/exceptions.cr
src/jennifer/view/mapping.cr

fix #414 
**General**
* upgrade supported mysql driver version to `0.14.0`
* upgrade supported pg driver version to `0.26.0`
**Model**
- add support for `JSON::PullParser` attribute class

Bump pg version and add JSON::PullParser support

---

.github/shard_1_3_2.yml
shard.yml
src/jennifer.cr
src/jennifer/generators/create_migration.cr
src/jennifer/generators/create_migration.ecr
src/jennifer/generators/field.cr
src/jennifer/migration/base.cr
src/jennifer/migration/table_builder/change_table.cr
src/jennifer/migration/table_builder/create_foreign_key.cr
src/jennifer/migration/table_builder/create_table.cr
src/jennifer/model/base.cr
src/jennifer/model/errors.cr
src/jennifer/model/resource.cr
src/jennifer/model/translation.cr
src/jennifer/relation/many_to_many.cr
src/jennifer/relation/polymorphic_belongs_to.cr

Address #423
**General**
* replace `phoffer/inflector.cr` inflector library with `luckyframework/wordsmith`

Change inflector to wordsmith

---

.github/workflows/ci.yml
spec/model/optimistic_locking_spec.cr
spec/models.cr
src/jennifer/model/optimistic_locking.cr

Fix a bug in reset_lock_version which decreases lock version incorrectly
We should only decrease lock version when it's changed
Please fill the corresponding section regarding this pull request notes below instead of modifying `CHANGELOG.md` file. Please remove all redundant sections before posting request.
**Model**
Fix the issue of Jennifer::Model::OptimisticLocking#reset_lock_version decreasing lock version column when it's not changed
@imdrasil

Fix issue that Jennifer::Model::OptimisticLocking#reset_lock_version decreases lock version column when it's not changed

---

.github/workflows/ci.yml
docs/migration.md
scripts/migrations/20191019010424611_add_all_type_model.cr
shard.yml
spec/model/base_spec.cr
spec/models.cr
spec/query_builder/eager_loading_spec.cr
src/jennifer/adapter.cr
src/jennifer/adapter/base.cr
src/jennifer/adapter/postgres.cr
src/jennifer/adapter/postgres/sql_generator.cr
src/jennifer/adapter/result_parsers.cr
src/jennifer/exceptions.cr
src/jennifer/model/json_converter.cr

Fix #439 
**Model**
* add support of `Array(Time)`, `Array(UUID)`, `Array(Bool)` types (for postgres)
* fix JSON column reading on eagerloading
**View**
* add support of `Array(Time)`, `Array(UUID)`, `Array(Bool)` types (for postgres)
**Adapter**
* `TypeCastError` raised during query execution is not wrapped into `Jennifer::BaseQuery` exception any more
* `Postgres` adapter converts `Array(Time)` to proper time zone when read from DB and to utc when write to DB
* `Postgres` adapter casts `Array(PG::BoolArray)`, `Array(PG::CharArray)`, `Array(PG::Int16Array)`, `Array(PG::Int32Array)`, `Array(PG::Float32Array)`, `Array(PG::Float64Array)`, `Array(PG::UUIDArray)`, `Array(PG::StringArray)`, `Array(PG::TimeArray)` to corresponding non-recursive array type (e.g. `Array(Bool)`)
**Exceptions**
* …

Fix JSON and array pg column reading

---

.github/run_integration_tests.sh
.github/setup_mysql.sh
.github/workflows/ci.yml

Fix bash syntax errors

---

README.md
spec/adapter/db_colorized_formatter_spec.cr
spec/adapter/db_formatter_spec.cr
spec/model/base_spec.cr
spec/support/config.cr
src/jennifer/adapter/base.cr
src/jennifer/adapter/db_colorized_formatter.cr
src/jennifer/adapter/db_formatter.cr

**Adapter**
- Adjust colors and format for colorize formatter
- change elapsed time display scale for formatters from microseconds to milliseconds

Adjust colors and format for colorize formatter
