imdrasil/jennifer.cr

spec/model/mapping_spec.cr, src/jennifer/model/mapping.cr
These should be `before_(create|save)` since they won't be saved if they are `after_(create|save)`.
=> fix with_timestamps

spec/model/base_spec.cr, spec/models.cr, spec/spec_helper.cr, src/jennifer/exceptions.cr, src/jennifer/model/base.cr, src/jennifer/model/scoping.cr, src/jennifer/query_builder/model_query.cr, src/jennifer/query_builder/query_object.cr
[Original Issue](https://github.com/imdrasil/jennifer.cr/issues/30)
Now as `%scope` argument could be used struct which is inherited from `Jennifer::QueryBuilder::QueryObject` and has implemented `#call` method
=> Add query object for scope

spec/config_spec.cr, spec/model/base_spec.cr, spec/spec_helper.cr, src/jennifer/adapter/base.cr, src/jennifer/config.cr, src/jennifer/exceptions.cr
I've been using Jennifer with some amber projects. The current generated database config in an amber project is in a url format (which is easily passed to crystal-db). I found myself parsing this into config for Jennifer in each and figured it would be nice to have Jennifer do this automatically.
=>  allow configuration via a db url

spec/adapter/postgres_spec.cr, src/jennifer/adapter/postgres.cr, src/jennifer/migration/table_builder/change_table.cr, src/jennifer/migration/table_builder/create_index.cr, src/jennifer/migration/table_builder/create_table.cr
passing nil for the type will create a default no frills index for the supplied field/fields. This allows for
```ruby
t.add_index("index_by_name", :name)
t.add_index("unique_name", :name, :uniq)
```
Might not hurt to extract the index functions to a module to avoid the duplication, what are your thoughts?
=> allow nil to be passed for the type of an index in a migration

spec/config.cr, spec/model/base_spec.cr, spec/query_builder/model_query_spec.cr, spec/spec_helper.cr, spec/view/base_spec.cr, src/jennifer/model/base.cr, src/jennifer/model/relation_definition.cr, src/jennifer/model/sti_mapping.cr, src/jennifer/query_builder/model_query.cr, src/jennifer/view/base.cr
- fixes `#includes` and `#eager_load` methods: marks empty relations as retrieved ones
- small test refactoring
- removed `Model::Base#search_by_sql` and `View::Base#search_by_sql` methods because of `QueryBuilder::ModelQuery#find_by_sql` method presence
- `RelationDefinition` macros optimization
=> Fix relation reloading after eager loading it

src/jennifer/migration/base.cr
Fix #72 `DropIndex` class reference in the migration class
=> Fix type for DropIndex class

src/jennifer/query_builder/i_model_query.cr, src/jennifer/query_builder/model_query.cr
Move next methods from `ModelQuery(T)` to `IModelQuery`:
- `#table`
- `#with(array)`
- `#includes` (all of them)
- `#preload` (all of them)
- `#eager_load` (all of them)
- `#relation`
- `#find_in_batches`
- `#find_each`
- `#destroy`
This will reduce code amount should be recompiled per each model
=> Move non model dependent methods to IModelQuery

docs/model_mapping.md, docs/validation.md, shard.yml, spec/factories.cr, spec/model/mapping_spec.cr, spec/model/sti_mapping_spec.cr, spec/model/validation_spec.cr, spec/models.cr, src/jennifer/model/validation.cr, src/jennifer/model/validation_messages.cr
- adds `allow_blank` (which is false by default) to the next validation macroses: `validates_inclucion`, `validates_exclusion`, `validates_format` and `validates_length`
- updated `ifrit` and `sam` versions
=> Add allow blank to some validations

README.md, docs/model_mapping.md, docs/view.md, examples/migrations/20170829000433679_add_materialized_view.cr, spec/model/base_spec.cr, spec/model/mapping_spec.cr, spec/model/sti_mapping_spec.cr, spec/models.cr, spec/view/base_spec.cr, spec/view/experimental_mapping_spec.cr, src/jennifer/adapter/base.cr, src/jennifer/adapter/postgres/migration/base.cr, src/jennifer/adapter/postgres/migration/table_builder/create_materialized_view.cr, src/jennifer/migration/base.cr, src/jennifer/migration/runner.cr, src/jennifer/migration/table_builder/change_table.cr, src/jennifer/model/mapping.cr, src/jennifer/model/sti_mapping.cr, src/jennifer/sam.cr, src/jennifer/view/experimental_mapping.cr
**breaking changes**
- now `Migration::Base#create_materialized_view` accepts `QueryBuilder::Query` for the 2nd argument instead of `String`
other changes:
- add automatic adding `null: true` if given field type in mapping is nillable (both for model and view)
- add `Primary32` and `Primary64` shortcuts for `Int32` and `Int64` primary fields (both for model and view)
- small refactoring of mapping macrosses
- small refactoring of `Adapter::Base` public interface
=> Add sugar to mapping

docs/model_sti.md, spec/adapter/base_spec.cr, spec/adapter/mysql_spec.cr, spec/adapter/postgres_spec.cr, spec/adapter/result_parsers_spec.cr, spec/config.cr, spec/model/mapping_spec.cr, spec/model/sti_mapping_spec.cr, spec/spec_helper.cr, src/jennifer/adapter/base.cr, src/jennifer/adapter/mysql.cr, src/jennifer/adapter/postgres.cr, src/jennifer/adapter/postgres/migration/table_builder/change_enum.cr, src/jennifer/exceptions.cr, src/jennifer/model/base.cr, src/jennifer/model/mapping.cr, src/jennifer/model/relation_definition.cr, src/jennifer/model/sti_mapping.cr, src/jennifer/query_builder/model_query.cr
- allows to load sti children classes using parent one during retrieving records from the db (e.g. `Parent.all.to_a` will return array of all subclasses depending on the `type` column)
- fixes several bugs in mysql adapter
- fixes `Model::Base#update_columns`
- fixes `Migration::TableBuilder::ChangeEnum` for postgres adapter
- extend tests suite
=> Fix sti loading

README.md, shard.yml, src/jennifer/adapter/base.cr, src/jennifer/migration/base.cr, src/jennifer/model/base.cr, src/jennifer/model/mapping.cr, src/jennifer/model/relation_definition.cr, src/jennifer/view/base.cr
Crystal 0.24 introduces [a couple of breaking changes](https://github.com/crystal-lang/crystal/releases/tag/0.24.0). The ones that affect `jennifer` are:
- Removing the `Time#ticks` method. `Time.measure` or `Time.monotonic` can be used instead (they provide nanosecond precision). See https://github.com/crystal-lang/crystal/pull/5093
- Removing the `macro def` construct (in favour of just calling def with macro syntax inside the method body). See https://github.com/crystal-lang/crystal/pull/5040
The `pg` shard has been updated [here](https://github.com/will/crystal-pg/issues/116), but it still uses a branch, because the changes are breaking. You can leave this PR unmerged until the `pg` shard changes get their own version and I can update the `shard.yml` accordingly (but I have no problem …
=> Prepare for Crystal 0.24

spec/model/relation_definition_spec.cr, src/jennifer/model/base.cr, src/jennifer/model/relation_definition.cr
- move all relation macros out of `included` macro to module level;
- avoid relation loading for a new record
=> Refactor relation definition macros

src/jennifer/adapter/base_sql_generator.cr, src/jennifer/query_builder/criteria.cr, src/jennifer/query_builder/criteria_container.cr, src/jennifer/query_builder/query.cr
- add `CriteriaContainer` to holder query orders - `Criteria#==` method is used for query dsl so can't be used to compare objects
=> Add criteria container for query orders

docs/callbacks.md, docs/validation.md, spec/model/base_spec.cr, spec/model/mapping_spec.cr, spec/query_builder/model_query_spec.cr, src/jennifer/model/base.cr, src/jennifer/model/mapping.cr, src/jennifer/query_builder/executables.cr, src/jennifer/query_builder/i_model_query.cr
adds following methods
- `Model::Base#update`
- `Model::Base#update!`
- `QueryBuilder::ModelQuery#path`
- `QueryBuilder::ModelQuery#path!`
- now - `QueryBuilder::ModelQuery#destroy` uses `#find_each` instead of `#to_a`
=> Update method enhancement

src/jennifer/query_builder/criteria_container.cr
Somewhy in Amber `Jennifer::QueryBuilder::CriteriaContainer`'s `@bucket : Hash(String, String)` returns `String | Nil` from the `#[]` method call. For now Have no idea why does this happen.
=> Add fix for CriteriaContainer yilding nilable

spec/model/base_spec.cr, spec/model/mapping_spec.cr, spec/model/parameter_converter_spec.cr, src/jennifer/adapter.cr, src/jennifer/adapter/shared/types.cr, src/jennifer/model/base.cr, src/jennifer/model/mapping.cr, src/jennifer/model/parameter_converter.cr
Adds `Jennifer::Model::Base.build_params` which allows to build `Hash(String, Jennifer::DBAny)` from `Hash(String, String)` respecting model attributes types.
=> Add model parameter converters

examples/migrations/20170122152105921_add_passport.cr, examples/migrations/20170410221437549_add_join_table.cr, examples/migrations/20170815112803321_add_model_with_one_field.cr, examples/migrations/20170916095004544_add_view.cr, src/jennifer/adapter/base.cr, src/jennifer/adapter/base_sql_generator.cr, src/jennifer/config.cr, src/jennifer/migration/base.cr, src/jennifer/migration/runner.cr, src/jennifer/migration/version.cr
- adds `Jennifer::Config.migration_failure_handler_method` configuration - represents which kind of method will be invoked if migration (any up or  down) is failed
- introduced failures callbacks: `#after_up_failure` & `#after_down_failure`
- now migration class name has no timestamp in name - version is retrieved from the file name
- any migration method and failure callbacks is wrapped into transaction
=> Migration version now is parsed from file name

docs/configuration.md, spec/config_spec.cr, spec/fixtures/database_with_nesting.yml, src/jennifer/config.cr
- now `Jennifer::Config::read` accepts block which returned value will be parsed for setting configuration parameters
=> Allow to specify document subpart for reading configuration

spec/model/base_spec.cr, spec/model/relation_definition_spec.cr, spec/models.cr, src/jennifer/model/base.cr, src/jennifer/model/relation_definition.cr, src/jennifer/model/resource.cr, src/jennifer/view/base.cr
- small refactoring of methods generated by relation definition macros.
- removes `Jennifer::Model::Base#relations`
- now relation objects are stored in constants
=> Refactor generated relation methods

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, README.md, docs/validation.md, shard.yml, spec/model/errors_spec.cr, spec/model/mapping_spec.cr, spec/model/translation_spec.cr, src/jennifer.cr, src/jennifer/exceptions.cr, src/jennifer/locale/en.yml, src/jennifer/model/authentication.cr, src/jennifer/model/base.cr, src/jennifer/model/errors.cr, src/jennifer/model/resource.cr, src/jennifer/model/translation.cr, src/jennifer/model/validation.cr, src/jennifer/validator.cr, src/jennifer/version.cr
- added last 0.5.1 changes from master
- added custom error container for models
Introducing own container for holding error messages increase the flexibility of customizing error messages.
Please fill the corresponding section regarding this pull request notes below instead of modifying `CHANGELOG.md` file.
**General**
- removes `accord` dependency
**Model**
- introduces new `Jennifer::Model::Errors` class replacing `Accord::ErrorList` which mimics analogic rails one a lot;
- moves `Translation::human_error` method functionality to introduced `Errors` instance level;
- `Resource#inspect` will ignore any instance attributes if `COLUMNS_METADATA` is not defined
=> Add custom errors container

.github/pull_request_template.md, docs/validation.md, src/jennifer/migration/table_builder/change_table.cr, src/jennifer/migration/table_builder/create_table.cr, src/jennifer/query_builder/criteria.cr
Replaces `Ifrit.typed_hash` macro usage in favor of standard language construction `{...} of K => V`. 
This will reduce (very slightly) compile time and runtime. Also, standard constructions are much preferable than synthetic macro.
**General**
- removes `Ifrit.typed_hash` and `Ifrit.typed_array` usage;
=> Replace ifrit typed macros with standard language construction

spec/adapter/sql_generator_spec.cr, spec/query_builder/join_spec.cr, spec/query_builder/query_spec.cr, src/jennifer/adapter/base_sql_generator.cr, src/jennifer/adapter/mysql/sql_generator.cr, src/jennifer/adapter/postgres/sql_generator.cr
Replaces `\n` character in sql with whitespace.
`\n` in logs breaks any log analyzing software. So It is more common to use whitespace for separating different parts of a query (even if it is less readable).
- now uses whitespace character instead of `\n` as query part separator
=> Remove line breaks in sql

src/jennifer/model/mapping.cr
This fixes
`Expected PG::Numeric but got Nil`
when using numeric_converter in a nullable field, like
```Crystal
price: {type: Float64, numeric_converter: :to_f64, null: true}
```
=> Fix issue in mapping DB values when using `numeric_converter` with nullable fields

docs/migration.md, examples/migrations/20170119011451314_create_contacts.cr, examples/migrations/20170119011507724_create_address.cr, examples/migrations/20170912145453751_add_index.cr, spec/adapter/base_spec.cr, spec/model/relation_definition_spec.cr, spec/query_builder/model_query_spec.cr, src/jennifer/adapter/base.cr, src/jennifer/adapter/postgres/migration/table_builder/change_enum.cr, src/jennifer/adapter/schema_processor.cr, src/jennifer/migration/base.cr, src/jennifer/migration/table_builder/base.cr, src/jennifer/migration/table_builder/change_table.cr, src/jennifer/migration/table_builder/create_foreign_key.cr, src/jennifer/migration/table_builder/create_index.cr, src/jennifer/migration/table_builder/create_table.cr, src/jennifer/migration/table_builder/drop_foreign_key.cr
Adds functionality regarding database foreign key constraint. ATM it supports only one field foreign key.
This increases the flexibility of database migration DSL.
**Migration**
- adds `Migration::TableBuilder::CreateForeignKey` & `Migration::TableBuilder::DropForeignKey`
- adds `Migration::Base#add_foreign_key` & `Migration::Base#drop_foreign_key`
- adds `Migration::TableBuilder::ChangeTable#add_foreign_key` & `Migration::TableBuilder::ChangeTable#drop_foreign_key`
=> Add foreign key support

docs/query_dsl.md, spec/adapter/sql_generator_spec.cr, spec/query_builder/all_spec.cr, spec/query_builder/any_spec.cr, spec/query_builder/condition_spec.cr, spec/query_builder/criteria_spec.cr, spec/query_builder/function_spec.cr, spec/query_builder/grouping_spec.cr, spec/query_builder/join_spec.cr, spec/query_builder/logic_operator_spec.cr, spec/query_builder/query_spec.cr, spec/query_builder/raw_sql_spec.cr, src/jennifer.cr, src/jennifer/adapter.cr, src/jennifer/adapter/base_sql_generator.cr, src/jennifer/query_builder/all.cr, src/jennifer/query_builder/any.cr, src/jennifer/query_builder/condition.cr, src/jennifer/query_builder/criteria.cr, src/jennifer/query_builder/function.cr, src/jennifer/query_builder/grouping.cr, src/jennifer/query_builder/join.cr, src/jennifer/query_builder/logic_operator.cr, src/jennifer/query_builder/query.cr, src/jennifer/query_builder/raw_sql.cr, src/jennifer/query_builder/sql_node.cr
Adds functionality for defining own sql functions. This allows easilly adding any kind of db-related function support into application.
**General**
- adds `Time::Span` to supported types
- allows listing any `SQLNode` instance in SELECT clause (like raw sql or funcitons)
- removes redundant `SQLNode#sql_args_count`
- adds `SQLNode#filterable?` function which presents if node has filterable sql parameter
- refactors `Condition#sql_arg`
- adds `Function` base abstract class for defining custom sql functions
- adds `lower`, `upper`, `current_timestamp`, `current_date`, `current_time`, `now`, `concat`, `abs`, `ceil`, `floor`, `round`
- adds `Join#filterble?` and `Query#filterable?`
=> Add custom sql function support

docs/model_mapping.md, docs/view.md, spec/model/mapping_spec.cr, spec/model/sti_mapping_spec.cr, spec/models.cr, src/jennifer/adapter/postgres.cr, src/jennifer/adapter/postgres/converters.cr, src/jennifer/model/base.cr, src/jennifer/model/converters.cr, src/jennifer/model/mapping.cr
- replaces mapping option `numeric_converter` with `converter` which allows specifying any kind of converter
- adds numeric-to-float64 and json converters
- small mapping optimizations
This allows defining custom converters for any kind of field.
**Model**
- replaces mapping option `numeric_converter` with new `converter`
- adds `NumericToFloat64Converter` and `JSONConverter`
- now `#to_h` and `#to_str_h` use field getter methods
=> Add field converters

.travis.spec.sh, docs/configuration.md, shard.yml, spec/adapter/base_spec.cr, spec/integration/concurrency_test.cr, spec/model/base_spec.cr, spec/spec_helper.cr, src/jennifer/adapter/base.cr, src/jennifer/adapter/base_sql_generator.cr, src/jennifer/adapter/transactions.cr, src/jennifer/config.cr, src/jennifer/model/converters.cr
Fix #156 and connection leak issue - when an exception is raised during transaction connection will not be released.
- add separa 
ATM `crystal-db` has some issue with idle connections in the connection pool so setting `max_idle_pool_size = max_pool_size = initial_pool_size` is the only way to ensure that application will use specified amount of connection.
**Model**
- remove `puts` from `JSONConverter#from_db`
**Adapter**
- propagate native `DB::Error` instead of wrapping it into `BadQuery`
- manually release a connection when an exception occurs under the transaction
**Config**
- set default `max_pool_size` to 1 and warn about dunger of setting different `max_pool_size`, `max_idle_pool_size` and `initial_pool_size`
=> Populate native exception from the driver during quering

src/jennifer/adapter/postgres/command_interface.cr
When using a custom port, the `config.port` is populated with the new port,
but the port is not used in the Jennifer::Postgres::CommandInterface methods.
this is fixed by updating #default_env_variables with the environment variable PGPORT:
```ruby
env.merge({"PGPORT" => config.port.to_s}) unless config.port == -1
```
Fix custom port not used in Postgres adapter.
I had an issue while creating the DB, it was using the default port even though I set up the custom port using `conf.port` and `#from_uri` both.
**Adapter**
- Fix custom port not used when accessing the Postgres database.
=> Fix custom port not used in postgres adapter

spec/model/base_spec.cr, src/jennifer/model/base.cr
Allow saving model instance with no changed fields.
```crystal
User.create.save # => true instead of false
```
**Model**
- `#save` and `#update` will return `true` when is called on an object with no changed fields (all before callbacks are invoked)
=> Return true when save persisted unchanged model

spec/model/base_spec.cr, spec/model/mapping_spec.cr, spec/model/sti_mapping_spec.cr, spec/view/base_spec.cr, spec/view/experimental_mapping_spec.cr, src/jennifer.cr, src/jennifer/adapter.cr, src/jennifer/adapter/postgres/migration/table_builder/change_enum.cr, src/jennifer/adapter/shared/types.cr, src/jennifer/migration/base.cr, src/jennifer/migration/table_builder/base.cr, src/jennifer/migration/table_builder/change_table.cr, src/jennifer/migration/table_builder/create_table.cr, src/jennifer/model/base.cr, src/jennifer/model/callback.cr, src/jennifer/model/mapping.cr, src/jennifer/model/relation_definition.cr, src/jennifer/model/resource.cr, src/jennifer/model/scoping.cr, src/jennifer/model/sti_mapping.cr, src/jennifer/model/translation.cr, src/jennifer/model/validation.cr, src/jennifer/query_builder/aggregations.cr, src/jennifer/query_builder/query.cr, src/jennifer/relation/base.cr, src/jennifer/relation/belongs_to.cr, src/jennifer/relation/relation_stub.cr, src/jennifer/view/base.cr, src/jennifer/view/experimental_mapping.cr
Remove documentation from the internal constructions or generated implementation of abstract methods
This removes unnecessary methods and constants from the generated application documentation. Fixes #163 . 
**General**
* add `:nodoc:` to all internal constants and generated methods (implementing standard ORM methods) from the macros
* `Query` isn't extended by `Ifrit`
**Model**
* next `Base` methods become abstract: `.primary_auto_incrementable?`, `.build_params`, `#destroy`, `#arguments_to_save`, `#arguments_to_insert`
* `Base#_extract_attributes` and `Base#_sti_extract_attributes` become **private**
* all callback invocation methods become **protected**
* next `Resource` methods become abstract: `.primary`, `.field_count`, `.field_names`, `.columns_tuple`, `#to_h`, …
=> Adjust documentation generating

docs/model_mapping.md, docs/query_dsl.md, docs/validation.md, spec/model/base_spec.cr, spec/models.cr, src/jennifer/adapter.cr, src/jennifer/config.cr, src/jennifer/macros.cr, src/jennifer/migration/base.cr, src/jennifer/migration/runner.cr, src/jennifer/migration/version.cr, src/jennifer/model/base.cr, src/jennifer/model/scoping.cr, src/jennifer/model/translation.cr, src/jennifer/query_builder/aggregations.cr, src/jennifer/query_builder/criteria.cr, src/jennifer/query_builder/query.cr, src/jennifer/query_builder/query_object.cr, src/jennifer/view/base.cr, src/jennifer/view/materialized.cr
- changes `Jennifer::QueryBulder:QueryObject` from struct to class
- extends existing documentation
- minor code clean-up
- fix a bug with `.scope(Symbol, QueryObject)` - adds `#respond_to?` for the similar readon as `.scope(Symbol, &block)` has 
* `QueryObject` now is an abstract class
* changed wording for the `ArgumentError` in `#max`, `#min`, `#sum`, `#avg` methods of `Aggregation` to "Cannot be used with grouping"
* change `Query#from(_from : String | Query)` signature to `Query#from(from : String | Query)` 
**Model**
* `Scoping.scope(Symbol,QueryObject)` now checks in runtime whether `T` of `Jennifer::QueryBuilder::ModelQuery(T)` responds to method named after the scope
**Migration**
* `.pending_versions`, `.assert_outdated_pending_migrations` and `.default_adapter` …
=> Refactor query object

docs/model_mapping.md
When using additional kinds of mappings like `JSON.mapping` in models, care must be taken to use the model `mapping` last so that none of the model's functionality is overwritten.
See issue #175
=> Clarify that model mapping must be used last

docs/query_dsl.md, spec/query_builder/expression_builder_spec.cr, src/jennifer/query_builder/criteria.cr, src/jennifer/query_builder/expression_builder.cr
Adds query builder shortcut for logic operators `AND`, `OR` and `XOR`.
```crystal
Post.all.where { and(_active, _likes > 10) } # WHERE (posts.active AND posts.likes > 10)
```
* add `ExpressionBuilder#and`, `ExpressionBuilder#or` and `ExpressionBuilder#xor` shortcut methods
=> Add logic operator shortcuts

docs/migration.md, examples/migrations/20170119011507724_create_address.cr, examples/migrations/20170122152105921_add_passport.cr, spec/adapter/base_spec.cr, spec/fixtures/generators/create_migration_with_references.cr, src/jennifer/adapter/base.cr, src/jennifer/adapter/mysql.cr, src/jennifer/adapter/postgres.cr, src/jennifer/generators/create_migration.ecr, src/jennifer/migration/base.cr, src/jennifer/migration/table_builder/create_table.cr, src/jennifer/query_builder/criteria.cr, src/jennifer/query_builder/query.cr, src/jennifer/query_builder/sql_node.cr
Invokes `#foreign_key` for the `Jennifer::Migration::TableBuilder::CreateTable#reference` 
**Adapter**
* add `Adapter#foreign_key_exists?`
**Migration**
* `TableBuilder::CreateTable#reference` triggers `#foreign_key`
=> Create foreign key for a reference table type

docs/crud.md, docs/validation.md, spec/query_builder/executables_spec.cr, src/jennifer/adapter/base_sql_generator.cr, src/jennifer/adapter/request_methods.cr, src/jennifer/query_builder/condition.cr, src/jennifer/query_builder/executables.cr, src/jennifer/query_builder/i_model_query.cr, src/jennifer/query_builder/query.cr
`Jennifer::QueryBuilder::Query#update` accepts block which allows to manually specify value to be set depending on other columns (or even same):
```crystal
Order.all.where { _created_at < current_date }.update do
{
:name => upper(_name),
:price => _price + 120 
}
end
```
* `Condition` includes `Statement`
* `Executables#update` accepts block expecting `Hash(Symbol, Statement)`
* `Executables#modify` is removed in favor of new `#update` method accepting block
* `.lock_clause` adds whitespaces around lock statement automatically
=> Extend query updating mechanism

spec/adapter/mysql/schema_processor_spec.cr, spec/adapter/postgres/schema_processor_spec.cr, spec/adapter/schema_processor_spec.cr, spec/support/fake_adapter.cr, spec/support/matchers.cr, src/jennifer/adapter/mysql.cr, src/jennifer/adapter/mysql/schema_processor.cr, src/jennifer/adapter/postgres/schema_processor.cr, src/jennifer/adapter/schema_processor.cr, src/jennifer/adapter/table_builder_builders.cr
* fixes rename table for postgres adapter (#186)
* fixes `#drop_foreign_key` sql syntax
**Adapter**
* add `Mysql::SchameProcessor`
* now `Base#schema_processor` is abstract
* add `Postgres::SchemaProcessor#rename_table`
* `SchemaProcessor` now is abstract
* all builder methods are moved from `SchemaProcessor` class to `TableBuilderBuilders` module
* fix syntax in `SchemaProcessor#drop_foreign_key`
=> Fix postgres rename table and drop foreign key syntax

docs/validation.md, spec/model/errors_spec.cr, spec/model/translation_spec.cr, spec/query_builder/function_spec.cr, src/jennifer/model/errors.cr, src/jennifer/model/resource.cr, src/jennifer/model/translation.cr
Adds all needed changes to allow `Jennifer::Model::Errors` usage by non-model class.
This reduce coupling and provide possibility of functionality re-usage.
**Model**
* `Translation` model now is includeable module
* all class methods of `Translation` are moved to `Translation::ClassMethods` which is automatically extended by target class using `extended` macro
* `#lookup_ancestors` and `#human_attribute_name` methods of `Translation` are added
* `Errors#base` now is type of `Translation` instead of `Base`
=> Decouple Model::Errors from Model::Base

.travis.setup.sh, docs/relations.md, examples/migrations/20180909200027509_create_note.cr, spec/factories.cr, spec/migration/table_builder_spec.cr, spec/model/base_spec.cr, spec/model/relation_definition_spec.cr, spec/models.cr, spec/query_builder/criteria_spec.cr, spec/relation/base_spec.cr, spec/relation/has_one_spec.cr, spec/relation/polymorphic_belongs_to_spec.cr, spec/relation/polymorphic_has_many_spec.cr, spec/relation/polymorphic_has_one_spec.cr, src/jennifer/migration/table_builder/change_table.cr, src/jennifer/migration/table_builder/create_table.cr, src/jennifer/model/base.cr, src/jennifer/model/mapping.cr, src/jennifer/model/relation_definition.cr, src/jennifer/model/resource.cr, src/jennifer/model/sti_mapping.cr, src/jennifer/query_builder/executables.cr, src/jennifer/query_builder/logic_operator.cr, src/jennifer/query_builder/query.cr, src/jennifer/relation/base.cr, src/jennifer/relation/has_one.cr, src/jennifer/relation/polymorphc_belongs_to.cr, src/jennifer/relation/polymorphic_has_many.cr, src/jennifer/relation/polymorphic_has_one.cr, src/jennifer/view/experimental_mapping.cr
Add polymorphic relationships: `belongs_to`, `has_many` and `has_one` 
- now `LogicOperator` is inherited from `SQLNode`
- `#delete` and `exists?` of `Executables` do nothing when `#do_nothing?` is `true`
- add `Query#do_nothing?`
- add `Query.null` which returns `Query.new.none`
**Model**
- add `Base#persisted?`
- now attribute-specific rendering for `Resource#inspect` is generated by `.mapping`
- add polymorphic relation support for `has_one`, `has_many` and `belongs_to` relations
- add `:nodoc:` for almost all generated relation methods (except `#association`)
- add missing relation names for criterion in `Relation::Base` methods
- add `Relation::IPolymorphicBelongsTo`, `Relation::PolymorphicHasMany` and `Relation::PolymorphicHasOne`
**View**
- now attribute-specific …
=> Polymorphic relations

src/jennifer/model/mapping.cr, src/jennifer/model/relation_definition.cr, src/jennifer/model/validation.cr
Fixes #190 
**Model**
* `@new_record`, `@destroyed`, `@errors`, changeset and relation attributes now is ignored by `JSON::Serializable`
=> Add all internal model variables to JSON::Serializable ignore

docs/command_line.md, src/jennifer/model/authentication.cr, src/jennifer/sam.cr, src/jennifer/validations/macros.cr, src/jennifer/validations/uniqueness.cr
- adjust authentication methods for the better integration with non-model classes
- make validations to explicitly use `Model#all` method
**General**
* add `db:seed` task as a placeholder seeding task
* `db:setup` now invokes `db:seed` after all `db:migrate`
**Model**
* add `skip_validation` argument to `Authentication.with_authentication` macro to specify whether validation should be added
=> Enhance model authentication methods and related validations

spec/query_builder/join_spec.cr, src/jennifer/query_builder/join.cr
`Jennifer::QueryBuilder::Join` now accepts `Grouping` as an `ON` section - it will be wrapped into `Condition`
* `Join` accepts `Grouping` for `ON` condition
=> Allow grouping being passed to Join

spec/model/mapping_spec.cr, src/jennifer/model/mapping.cr
Allow `Jennifer::Model::Base#attribute=` to accept not only defined type but also `Jennifer::DBAny`.
This was done to allow assignments of kind:
```crystal
hash = { :name => "name", :age => 99 }
user.name = hash[:name]
user.age = hash[:age]
```
**Model**
* allow `Jennifer::Model::Base#attribute=` to accept not only defined type but also `Jennifer::DBAny`
=> Allow model setter to accept DBAny

docs/crud.md, spec/model/base_spec.cr, src/jennifer/model/base.cr
Renames `Model::Base#update_attributes` to `#set_attributes` as this method just sets values and doesn't perform saving (#198 ).
**Model**
* rename `Base#update_attributes` to `Base#set_attributes`
=> Rename Model#update_attributes to #set_attributes

docs/crud.md, spec/adapter/base_spec.cr, src/jennifer/adapter/base.cr, src/jennifer/adapter/base_sql_generator.cr, src/jennifer/adapter/postgres.cr, src/jennifer/adapter/postgres/schema_processor.cr, src/jennifer/adapter/record.cr, src/jennifer/migration/table_builder/create_view.cr, src/jennifer/query_builder/criteria.cr, src/jennifer/query_builder/model_query.cr, src/jennifer/relation/has_one.cr
- unify `#parse_query` method by adapter and sql generator - sql generator returns only string of SQL
- all `_query` arguments in `Adapter::Base` methods renamed to `query`
**Adapter**
* all `_query` arguments in `Base` methods are renamed to `query`
* `Base.extract_arguments` is removed
* `.delete`, `.exists` and `.count` of `BaseSQLGenerator` now returns string
* `Postgres.bulk_insert` is removed
=> Unify #parse_query usage by adapter and sql generator

src/jennifer/migration/runner.cr
Fix schema file keep generating with skip_dumping_schema_sql set to true.
**Config**
* fix ignoring `skip_dumping_schema_sql` config
=> fix schema generating with skip_dumping_schema_sql set to true

spec/query_builder/executables_spec.cr, src/jennifer/adapter/request_methods.cr, src/jennifer/config.cr, src/jennifer/exceptions.cr, src/jennifer/model/base.cr, src/jennifer/query_builder/executables.cr
Make message of `RecordNotFound` more descriptive
**Exceptions**
* 'RecordNotFound' from `QueryBuilder::Query#first!` and `QueryBuilder::Query#last!` includes detailed parsed query
=> Make message of RecordNotFound more descriptive

docs/configuration.md, src/jennifer/adapter/shared/types.cr, src/jennifer/config.cr
Introduces `pool_size` configuration to set 3 pool configs at once.
**Config**
* introduce new configuration `pool_size` which sets `max_idle_pool_size = max_pool_size = initial_pool_size` to the given value; getter `#pool_size` returns `#max_pool_size`
* `postgres` is no more default adapter
=> Add pool_size configuration

CHANGELOG.md, README.md, docs/authentication.md, docs/configuration.md, docs/migration.md, docs/model_mapping.md, docs/query_dsl.md, docs/relations.md, spec/query_builder/condition_spec.cr, spec/query_builder/query_spec.cr, src/jennifer/adapter/mysql/schema_processor.cr, src/jennifer/adapter/postgres/schema_processor.cr, src/jennifer/migration/table_builder/base.cr, src/jennifer/model/base.cr, src/jennifer/model/scoping.cr, src/jennifer/model/translation.cr, src/jennifer/query_builder/nested_relation_tree.cr, src/jennifer/query_builder/relation_tree.cr
- minor fixes in migration logic
- documentation wording fixes
**Adapter**
* `Mysql::SchemaProcessor` now respects `false` as column default value
* `Postgres::SchemaProcessor` now respects `false` as column default value
**Migration**
* `TableBuilder::Base::AllowedTypes` alias includes `Float64` and `JSON::Any`
=> Fix migrating column changing logic

shard.yml, spec/query_builder/executables_spec.cr, spec/query_builder/query_spec.cr, spec/spec_helper.cr, src/jennifer/query_builder/executables.cr, src/jennifer/query_builder/i_model_query.cr, src/jennifer/query_builder/model_query.cr
Make all executable methods respect `Jennifer::QueryBuilder::Query#none`; fix #215.
* `#pluck`, `#update`, `#db_results`, `#results`. `#each_result_set` and `#find_in_batches`of `Query` respects `#none` (returns empty result if it has being called)
=> Revise #none

CHANGELOG.md, README.md, shard.yml, src/jennifer.cr, src/jennifer/query_builder/query_object.cr
Bump version to `0.7.1`.
* remove deprecated `QueryObject` constructor accepting array of options and `#params`
=> Bump to 0.7.1

.travis.yml, spec/query_builder/executables_spec.cr, src/jennifer/adapter/base.cr, src/jennifer/adapter/base_sql_generator.cr, src/jennifer/adapter/mysql/sql_generator.cr, src/jennifer/adapter/postgres/criteria.cr, src/jennifer/adapter/postgres/sql_generator.cr, src/jennifer/model/base.cr, src/jennifer/query_builder/aggregations.cr, src/jennifer/query_builder/executables.cr, src/jennifer/query_builder/expression_builder.cr, src/jennifer/query_builder/values.cr
Adds upsert command support mentioned in #139 .
* remove redundant `Criteria#similar` which is loaded with `postgres` adapter
* add `Query#insert`
* add `Query#upsert`
* add `ExpressionBuilder#values` and `Values` to reference to `VALUES` statement in upsert
**Adapter**
* remove `Base::ArgType` alias
* add `Base#upsert`
* add `.insert_on_duplicate` and `.values_expression` to `BaseSQLGenerator` as abstract methods and implementations to `Postgres` and `Mysql`
=> Add query upsert command

examples/migrations/20181017202211501_create_column_alias_models.cr, spec/factories.cr, spec/model/base_spec.cr, spec/model/mapping_spec.cr, spec/model/sti_mapping_spec.cr, spec/models.cr, spec/view/mapping_spec.cr, spec/views.cr, src/jennifer/model/mapping.cr, src/jennifer/model/sti_mapping.cr, src/jennifer/validations/macros.cr, src/jennifer/view/mapping.cr
Hi,
this should be some sort of proof-of-concept for #218.
In order to overcome some issues with an existing database / domain model, we require some way to get an abstraction layer between the field names and the underlying columns.
This feature adds a new mapping option `column` to define custom column names for fields.
A mapping for a class like
```
class A < Jennifer::Model::Base
mapping({
id: Primary64,
b: {type: String, colum: :c}
})
end
```
would therefore map to a table `A(id INTEGER, c TEXT)` (ignoring the actual types in this example) while still allowing access to property `b`.
This is done by manually gathering the column mappings via macros and then replacing any access to the column name with this mapping (e.g. `fields << {{COLUMN_MAPPINGS[attr.id]}}` i/o `fields << …
=> Allow custom field names for mapped columns

spec/spec_helper.cr, spec/support/matchers.cr, spec/validations/absence_spec.cr, spec/validations/acceptance_spec.cr, spec/validations/confirmation_spec.cr, spec/validations/exclusion_spec.cr, spec/validations/format_spec.cr, spec/validations/inclusion_spec.cr, spec/validations/length_spec.cr, spec/validations/numericality_spec.cr, spec/validations/presence_spec.cr, spec/validations/uniqueness_spec.cr, src/jennifer/validations/numericality.cr
Fix `odd` and `even` numeric validator options for non integer arguments (fix #224 )
**Validation**
* fix `odd` and `even` numeric validator options for non integer arguments
=> Fix odd and even options of numericality validator

docs/validation.md
This is just fixing a small typo in the documentation for validates_uniqueness, the corresponding method has an "s".
=> fixing validates_uniqueness typo in the documentation

docs/model_mapping.md, docs/timestamps.md, spec/model/mapping_spec.cr, spec/models.cr, spec/query_builder/function_spec.cr, spec/relation/polymorphic_belongs_to_spec.cr, src/jennifer/adapter/postgres/converters.cr, src/jennifer/macros.cr, src/jennifer/model/callback.cr, src/jennifer/model/common_mapping.cr, src/jennifer/model/converters.cr, src/jennifer/model/field_declaration.cr, src/jennifer/model/mapping.cr, src/jennifer/model/resource.cr, src/jennifer/model/sti_mapping.cr
Allows defining reusable column mapping in modules and abstract classes.
Requested here #229 this functionality allows to make some common mapping (like id definition, `created_at`, `updated_at` columns) and reuse it across application.
**Model**
* `Mapping` module now can be included by another module with mapping definition
* `STIMapping` now doesn't convert result set to hash and use same logic as `Mapping`
**View**
* mapping shares same functionality as `Model`
=> Add model mapping inheritance

spec/query_builder/condition_spec.cr, spec/query_builder/criteria_spec.cr, src/jennifer/query_builder/condition.cr, src/jennifer/query_builder/criteria.cr
Allow passing empty array to `IN` operator. This will add `1 = 0` condition to a result SQL.
* allow passing empty array to `Criteria#in`
=> Allow passing empty array to IN operator

spec/query_builder/function_spec.cr, src/jennifer/adapter/base.cr
Hi.
It's not necessary here :)
In "ifrit" you have the class called `HashWithIndifferentAccess`, which triggers a Crystal bug, it unable to compile jennifer.cr with raven.cr - https://github.com/Sija/raven.cr/issues/49.
I guess `HashWithIndifferentAccess` not used in this shard.
=> remove redundant require of ifrit

spec/adapter/base_spec.cr, spec/query_builder/function_spec.cr, src/jennifer/adapter/base.cr, src/jennifer/adapter/mysql.cr, src/jennifer/adapter/postgres.cr, src/jennifer/adapter/record.cr, src/jennifer/migration/version.cr, src/jennifer/model/base.cr, src/jennifer/query_builder/aggregations.cr, src/jennifer/query_builder/function.cr, src/jennifer/query_builder/query.cr
Loads tables column counts in one request instead of separate ones
**Adapter**
* speed-up tables column count fetch at application start-up
* add next SQL functions: `count`, `sum`, `avg`, `min`, `max`
**Record**
* For missing fields `BaseException` exception is raised instead of `KeyError`
=> Increase performance of warming up on startup; add aggregation sql functions

src/jennifer/adapter/base.cr, src/jennifer/adapter/postgres.cr, src/jennifer/query_builder/executables.cr
This pull request restricts the APIs of `Executables#exists?`, `Jennifer::Adapter::Base#exists?` and `Jennifer::Adapter::Postgres#exists?` to always return results of type `Bool`.
Related issue: #241
- Fix result type of `Executables#exists?` query method to `Bool`
**Adapter**
- Fix result type of `#exists?` query method to `Bool` for `Base` and `Postgres` adapters
=> Restrict result type of Executables#exists? to Bool

docs/command_line.md, spec/integration/sam_test.cr, src/jennifer/adapter/base.cr, src/jennifer/adapter/command_shell/i_command_shell.cr, src/jennifer/adapter/db_command_interface.cr, src/jennifer/adapter/mysql.cr, src/jennifer/adapter/mysql/command_interface.cr, src/jennifer/adapter/postgres/command_interface.cr, src/jennifer/migration/runner.cr
Allow to invoke `sam db:create` when database already exists without getting any error
This simplifies deployment process.
**General**
* `db:create` command doesn't fail if database already exists
=> Doesn't fail on db:create when database already exists

docs/model_mapping.md, spec/model/base_spec.cr, spec/model/mapping_spec.cr, spec/models.cr, src/jennifer/model/mapping.cr
Add `:auto` key to model mapping to mark integer primary key as not autoincrementable.
**Model**
* add `:auto` mapping option to specify whether primary key is autoincrementable
=> Add model primary key autoincrementation configuration

README.md, spec/adapter/mysql_spec.cr, spec/adapter/postgres_spec.cr, spec/query_builder/executables_spec.cr, src/jennifer/adapter/base.cr, src/jennifer/adapter/base_sql_generator.cr, src/jennifer/adapter/mysql.cr, src/jennifer/adapter/postgres.cr, src/jennifer/query_builder/executables.cr
Add `#explain` method to the query which returns formatted output of `EXPLAIN` sql.
* add `Executables#explain`
**Adapter**
* add `Base#explain` abstract method and implementations for `Mysql` and `Postgres`
* add `.explain`
=> Add query explain

docs/model_mapping.md, shard.yml, spec/model/sti_mapping_spec.cr, spec/models.cr, spec/query_builder/aggregations_spec.cr, spec/query_builder/function_spec.cr, spec/support/matchers.cr, spec/views.cr, src/jennifer/adapter/postgres.cr, src/jennifer/adapter/postgres/converters.cr
Fixes #258 . As a result all string-based fields mapping to Postrge `ENUM` should take `Jennifer::Model::EnumConverter` converter.
**General**
* add `crystal-pg` 0.18.0 support
**Model**
* Add `EnumConverter` converter for Postgre `ENUM` field convert
* (pg only) field presenting `ENUM` field should explicitly specify `converter: Jennifer::Model::EnumConverter`
**Adapter**
* `Postgre` adapter now doesn't register decoders for each ENUM type in `#prepare`
=> Add Postgre ENUM converter to String

src/jennifer/migration/table_builder/base.cr
Extends `Jennifer::Migration::TableBuilder::Base::AllowedTypes` alias with `Int64` type.
**Migration**
* extend `Jennifer::Migration::TableBuilder::Base::AllowedTypes` alias with `Int64` type.
=> Add Int64 to Jennifer::Migration::TableBuilder::Base::AllowedTypes alias

docs/configuration.md, src/jennifer.cr, src/jennifer/config.cr, src/jennifer/migration/runner.cr
Fix missing `JSON` bug and add `allow_outdated_pending_migration`
Please fill the corresponding section regarding this pull request notes below instead of modifying `CHANGELOG.md` file. Please remove all redundant sections before posting request.
**General**
* fix bug with not defined `JSON`
**Config**
* add `allow_outdated_pending_migration` configuration to specify whether outdated pending migration should be silently processed or error should be raised
=> Add allow_outdated_pending_migration_option

examples/migrations/20180909200027509_create_notes.cr, spec/migration/base_spec.cr, spec/migration/runnser_spec.cr, spec/spec_helper.cr, src/jennifer/migration/base.cr, src/jennifer/migration/runner.cr
Add an option to disable automatic transaction wrapping of migration methods
**Migration**
* add `Base.with_transaction` method to disable automatic transaction wrapping around migration methods
* add `Base.with_transaction?` to check whether migration is run under a transaction
=> Add option to disable automatic transaction wrapping of migration methods

docs/migration.md, docs/time.md, examples/migrations/20191019010424611_add_all_type_model.cr, spec/migration/table_builder/create_table_spec.cr, spec/model/mapping_spec.cr, spec/models.cr, src/jennifer/adapter.cr, src/jennifer/adapter/mysql.cr, src/jennifer/adapter/postgres.cr, src/jennifer/migration/table_builder/change_table.cr, src/jennifer/migration/table_builder/create_index.cr, src/jennifer/migration/table_builder/create_table.cr, src/jennifer/model/common_mapping.cr, src/jennifer/model/mapping.cr, src/jennifer/view/mapping.cr
Fix #275 and several minor tweaks.
**Model**
* fix bug with primary field presence assertion
**View**
* fix bug with primary field presence assertion
**Adapter**
* add `date` SQL data type
* `date_time` field type maps to `timestamp` SQL data type (postgres only)
**Migration**
* remove `var_string` field type
* remove `blob` field type for postgres
* fix wrong explanation message for `TableBuilder::CreateIndex`
* add new `TableBuilder::CreateTable#index` signatures (old ones are deprecated):
* `#index(fields : Array(Symbol), type : Symbol | ::Nil = nil, name : String | ::Nil = nil, lengths : Hash(Symbol, Int32) = {} of Symbol => Int32, orders : Hash(Symbol, Symbol) = {} of Symbol => Symbol)`
* `#index(field : Symbol, type : Symbol | ::Nil = nil, name : String | ::Nil = nil, length : Int32 …
=> Fix sql data type mapping and some api

spec/adapter/schema_processor_spec.cr, spec/migration/table_builder/create_foreign_key_spec.cr, src/jennifer/adapter/schema_processor.cr, src/jennifer/migration/base.cr, src/jennifer/migration/table_builder/base.cr, src/jennifer/migration/table_builder/change_table.cr, src/jennifer/migration/table_builder/create_foreign_key.cr, src/jennifer/migration/table_builder/create_table.cr
Slightly adjust `on_delete` and `on_update` foreign key options support
**Migration**
* `Base#add_foreign_key` accepts `on_delete` and `on_update` keyword arguments to specify corresponding actions 
* `TableBuilder::ChangeTable#add_foreign_key` accepts `on_delete` and `on_update` keyword arguments to specify corresponding actions 
* `TableBuilder::CreateTable#reference` accepts `on_delete` and `on_update` options to specify corresponding actions 
* `TableBuilder::CreateTable#foreign_key` accepts `on_delete` and `on_update` keyword arguments to specify corresponding actions
=> Adjust migration ON ACTION functionality

spec/adapter/result_parsers_spec.cr, spec/model/mapping_spec.cr, spec/spec_helper.cr, src/jennifer/adapter/mysql.cr, src/jennifer/adapter/result_parsers.cr, src/jennifer/model/field_declaration.cr, src/jennifer/model/mapping.cr, src/jennifer/model/sti_mapping.cr, src/jennifer/query_builder/i_model_query.cr, src/jennifer/query_builder/nested_relation_tree.cr, src/jennifer/query_builder/relation_tree.cr, src/jennifer/view/mapping.cr
Fix #279 
* use adapter's `#read_column` in `NestedRelationTree`
* add `RelationTree#adapter`
**Adapter**
* fix issue with treating `tinyint` mysql field as `boolean`
* remove `ResultParser#result_to_array`
* add `Mysql#read_column`
=> Fix wrong casting of any Int8 field to Bool when reading result set to hash in MySQL

docs/configuration.md, docs/getting_started.md, docs/migration.md, examples/migrations/20170119011451314_create_contacts.cr, examples/migrations/20170119011460000_remove_enum_value.cr, spec/adapter/base_spec.cr, spec/adapter/mysql/sql_generator_spec.cr, spec/adapter/postgres/sql_generator_spec.cr, spec/generators/migration_spec.cr, spec/generators/model_spec.cr, spec/migration/base_spec.cr, spec/model/base_spec.cr, src/jennifer/adapter/base.cr, src/jennifer/adapter/base_sql_generator.cr, src/jennifer/adapter/json_encoder.cr, src/jennifer/adapter/mysql.cr, src/jennifer/adapter/mysql/sql_generator.cr, src/jennifer/adapter/postgres.cr, src/jennifer/adapter/postgres/quoting.cr, src/jennifer/adapter/postgres/schema_processor.cr, src/jennifer/adapter/postgres/sql_generator.cr, src/jennifer/adapter/quoting.cr, src/jennifer/adapter/transaction_observer.cr, src/jennifer/adapter/transactions.cr, src/jennifer/config.cr, src/jennifer/query_builder/ordering.cr
Fixes the case when we what to import total count of values that exceeds maximum allowed. In a such case all arguments will be just quoted.
**Adapter**
* add `Base.default_max_bind_vars_count` which returns default maximum count of bind variables that can be used in `Base#bulk_insert` (default is 32766)
* `Mysql.default_max_bind_vars_count` and `Postgres.default_max_bind_vars_count` returns `32766` 
* `Base#bulk_insert` doesn't do table lock no more
* if variables that should be inserted by `Base#bulk_insert` exceed `Base.max_bind_vars` all of them are quoted and put into a query
* remove `BaseSQLGenerator::ARRAY_ESCAPE`
* move `BaseSQLGenerator::ARGUMENT_ESCAPE_STRING` to `Quoting`
* move `BaseSQLGenerator` `.quote`, `.escape_string`, `.filter_out` to `Quoting`
* add correct values …
=> Add quoting for huge bulk inserts instead of prepared statement usage

.gitignore, docs/model_mapping.md, docs/pagination_and_ordering.md, spec/model/base_spec.cr, spec/models.cr, spec/query_builder/order_expression_spec.cr, spec/relation/polymorphic_belongs_to_spec.cr, src/jennifer/adapter/base_sql_generator.cr, src/jennifer/adapter/mysql/sql_generator.cr, src/jennifer/adapter/postgres/sql_generator.cr, src/jennifer/model/resource.cr, src/jennifer/query_builder/criteria.cr, src/jennifer/query_builder/order_expression.cr, src/jennifer/query_builder/ordering.cr, src/jennifer/query_builder/query.cr
Fix #288 .
* `OrderItem` is renamed to `OrderExpression` to avoid possible name collisions
**Model**
* `Resource.table_prefix` now returns underscored namespace name (if any) by default
=> Fix possible name collision; fix model table name prefix generating

src/jennifer/migration/table_builder/create_table.cr
Fixed a bug where the `type` parameter of the `CreateTable#reference` method was invalid
What is happening now is that, regardless of the value of the `type` parameter, the resulting SQL will always be of type integer.
This PR's commits is based on the `v0.8.4` tag, not the master branch. Because the master branch currently has compilation errors.
=> reference type fix

spec/model/mapping_spec.cr, spec/model/translation_spec.cr, src/jennifer/model/base.cr, src/jennifer/model/mapping.cr, src/jennifer/model/presentable.cr, src/jennifer/model/translation.cr, src/jennifer/model/validation.cr
Add `Jennifer::Presentable` to formalize abstract interface for the dynamic access to model metadata and attribute interface.
**General**
* add `Jennifer::Presentable` with abstract methods declarations (`#attribute`, `#errors`, `#human_attribute_name`, `#attribute_metadata`, `#class_name`)
**Model**
* `Base` includes `Jennifer::Presentable`
* add `Translation#class_name` method to return underscored class name
* add `Mapping#attribute_metadata` to return attribute metadata by it's name
=> Add presentable interface

spec/migration/table_builder/change_table_spec.cr, spec/migration/table_builder/create_table_spec.cr, src/jennifer/migration/base.cr, src/jennifer/migration/table_builder/base.cr, src/jennifer/migration/table_builder/change_table.cr, src/jennifer/migration/table_builder/create_table.cr
**Migration**
* add `#add_reference`, `#drop_reference`, `#add_timestamps` to `TableBuilder::CHangeTable`
* `TableBuilder::CHangeTable#drop_index` also accepts single column name
* remove deprecated `TableBuilder::CreateTable#index` overrides
=> Make migration DSL a bit more consistent

src/jennifer/model/base.cr
If you have a `Jennifer::Model::Base` subclass named `Model` or `Record`, Jennifer can't compile with an error like so:
```
In lib/jennifer/src/jennifer/adapter/base.cr:44:24
44 | models[model.table_name] << model
^---------
Error: undefined method 'table_name' for Jennifer::Record.class (compile-time type is (Jennifer::Model::Base.class | Jennifer::Record.class))
```
The macro producing  `Jennifer::Model::Base.models` is accidentally including `Jennifer::Record` instead of `::Record` in the return value, so the type is now a union which breaks stuff. Instead, `#models` should return `::Record`, which can be accomplished by changing the macro to use a fully qualified name! https://crystal-lang.org/api/0.32.1/Crystal/Macros/TypeNode.html#name:MacroId-instance-method says that the `#name` …
=> Use fully qualified model name references in the models macro 

docs/authentication.md
It fixes a typo in the authentication document's last code example.
=> Fix typo in authentication document

src/jennifer/adapter/postgres/sql_generator.cr
This PR fixes a potential compilation issue that appears in certain edge cases where the explicit typecast during SQL generation somehow confuses the type inference.
This does not seem to be a frequent issue as it only ever happened to me in one occasion where I had two models *without* date / timestamp columns (the following are abstractions of those)
```crystal
class Sample < Jennifer::Model::Base
table_name "samples"
mapping({
id:             Int64,
name:       String?,
secret:      String?
})
has_and_belongs_to_many :others, Other, join_table: "sample_others", association_foreign: "other_id", foreign: "sample_id"
end
```
```crystal
class Other < Jennifer::Model::Base
table_name "others"
mapping({
id:             Int64,
title:       String?
})
end
```
which are connected via a …
=> Fix issue where cast confuses type inference

spec/adapter/base_sql_generator_spec.cr, src/jennifer/adapter/base_sql_generator.cr
This PR fixes an issue in the SQL query builder where multiple recursive CTEs would lead to invalid SQL.
As an example, the following construct
```crystal
Jennifer::Query["contacts"]
.with("test", Contact.all, false)
.with("test2", Address.all, true)
```
previously resulted in the following SQL
```sql
WITH test AS (SELECT contacts.* FROM contacts ) , RECURSIVE test2 AS (SELECT addresses.* FROM addresses ) 
```
According to both [PostgreSQL](https://www.postgresql.org/docs/13/queries-with.html) and [MySQL](https://dev.mysql.com/doc/refman/8.0/en/with.html#common-table-expressions-recursive) specs, the `RECURSIVE` keyword has to appear *once* at the top if *any* of the given CTEs uses recursion - the current implementation violates both of those rules.
The valid version would be 
```sql …
```
=> Hoist RECURSIVE keyword to the top of CTE list

spec/query_builder/query_spec.cr, src/jennifer/query_builder/query.cr
This PR relaxes the type restriction on `Jennifer::QueryBuilder::Query#with` from requiring the `self` type on the corresponding query to using the supertype `Query` itself. Since CTEs often query resources from other tables, it probably makes more sense to allow arbitrary query types for CTEs (e.g. mixing different model queries, model queries and raw queries, etc.).
While the previous type restriction still worked for some of those cases, I experienced weird behaviour that could only be fixed that way.
As an example, while the following query compiled correctly
```crystal
Address.all
.with("acontacts", Contact.all.where { sql("contacts.name LIKE %s", ["A%"]) })
.join("acontacts") { _acontacts__id == _addresses__contact_id }
.pluck(:street).should eq ["Test street 1"]
```
this one (only …
=> Relax CTE query type to allow more flexible query combinations

src/jennifer/adapter/transactions.cr
Hi,
we discovered (and correct me if I'm wrong here) that Jennifer actually does not seem to use the [reconnect facilities](https://github.com/crystal-lang/crystal-db/blob/ed686ad3015f48f8b22cf4fbec80e8c8088ef44b/src/db/pool.cr#L142-L168) of the main Crystal DB shard. 
This pull request therefore replaces the manual connection checkout/releases with calls to the provided APIs that also ensure that reconnects are performed - otherwise the `retry_attempts` flag is actually useless for model and transactional queries.
This PR is still sort of WIP as we are still unsure about how to handle the "cached" transactional connections in the `Transactions` class. Is retrying there even a goal? Would a retry then automatically begin a new transaction?
Therefore, we are open for feedback of any kind …
=> [WIP] Ensure reconnects are performed when connection is lost

.github/pull_request_template.md, README.md, docs/validation.md, shard.yml, spec/model/relation_definition_spec.cr, spec/model/validation_spec.cr, spec/models.cr, spec/spec_helper.cr, spec/validations/numericality_spec.cr, src/jennifer/adapter/base.cr, src/jennifer/adapter/base_sql_generator.cr, src/jennifer/adapter/mysql.cr, src/jennifer/adapter/postgres.cr, src/jennifer/adapter/schema_processor.cr, src/jennifer/model/base.cr, src/jennifer/model/resource.cr, src/jennifer/relation/i_relation.cr, src/jennifer/relation/polymorphic_belongs_to.cr, src/jennifer/validations/absence.cr, src/jennifer/validations/acceptance.cr, src/jennifer/validations/confirmation.cr, src/jennifer/validations/exclusion.cr, src/jennifer/validations/format.cr, src/jennifer/validations/inclusion.cr, src/jennifer/validations/length.cr, src/jennifer/validations/macros.cr, src/jennifer/validations/numericality.cr, src/jennifer/validations/presence.cr, src/jennifer/validations/uniqueness.cr, src/jennifer/validations/validator.cr
Address #360 
**General**
* add crystal 0.36.1 support
* fix inconsistent method signatures in multiple places
**Validation**
* change `Validator#validate` abstract interface to `#validate(record, **opts)`
* update all built-in validators to reflect new `Validator` interface
* make `Validator.with_blank_validation` macro to accept arguments to reference record, field name, value and blank value acceptance
**Relation**
* remove abstract `#condition_clause` & `#condition_clause(a)` declarations from `IRelation`
**Adapter**
* remove abstract `#update`  declaration from `Base`
=> Add crystal 0.36.1 support

shard.yml
I updated the Crystal version so that I can use this shard in my new Amber application that uses Crystal 1.0
Updated the shard file, and was able to setup a local test DB and run all specs with the following results:
```bash
Finished in 7.83 seconds
1789 examples, 0 failures, 0 errors, 94 pending
```
Adds support for any official releases of Crystal from 0.36.1 - 1.x.x specifically allowing for any of the minor releases because Crystal 1.x is supposed to avoid any breaking changes until Crystal 2.0
=> Added support for Crystal 0.36.1 - 1.x.x

spec/model/mapping_spec.cr, src/jennifer/model/mapping.cr
Fix before_save callbacks generated by macro `with_timestamps`
created_at and updated_at should be set dirty in order to get injected into the UPDATE sql
Please fill the corresponding section regarding this pull request notes below instead of modifying `CHANGELOG.md` file. Please remove all redundant sections before posting request.
**Model**
Fix a bug where updated_at is not set in the generated sql qeury from model.save
=> created_at and updated_at should be dirty after the default before_save callbacks

.github/workflows/ci.yml, spec/model/base_spec.cr, spec/model/big_decimal_converter_spec.cr, spec/model/coercer_spec.cr, spec/model/errors_spec.cr, spec/model/mapping_spec.cr, spec/model/numeric_to_float64_converter_spec.cr, spec/model/time_zone_converter_spec.cr, spec/model/timestamp_spec.cr, spec/model/validation_spec.cr, src/jennifer/adapter/postgres/model/numeric_to_float64_converter.cr, src/jennifer/model/base.cr, src/jennifer/model/big_decimal_converter.cr, src/jennifer/model/errors.cr, src/jennifer/model/mapping.cr, src/jennifer/model/time_zone_converter.cr, src/jennifer/model/timestamp.cr
**Model**
* `NumericToFloat64Converter`, `BigDecimalConverter`, `TimeZoneConverter` `#from_hash` accepts string as field value
* `BigDecimalConverter#from_hash` accepts integer and float values as field value 
* fix `Errors#inspect` bug using old `UInt64#to_s` signature
* introduce `Timestamp` module that now includes `with_timestamps` macro
* reworked how `updated_at` and `created_at` fields are set before save - now they are set explicitly without utilizing callbacks
=> Extend some converters to support string values in `.from_hash` method

docs/configuration.md, spec/query_builder/expression_builder_spec.cr, spec/query_builder/query_spec.cr, src/jennifer/adapter/base_sql_generator.cr, src/jennifer/adapter/quoting.cr, src/jennifer/adapter/record.cr, src/jennifer/config.cr, src/jennifer/model/base.cr, src/jennifer/model/mapping.cr, src/jennifer/model/resource.cr, src/jennifer/model/timestamp.cr, src/jennifer/query_builder/criteria.cr, src/jennifer/query_builder/executables.cr, src/jennifer/query_builder/expression_builder.cr, src/jennifer/query_builder/i_model_query.cr, src/jennifer/query_builder/query.cr, src/jennifer/view/base.cr
Introduces `#where` query method that accepts hash with keys representing table columns and values representing desired values. Currently it accepts only Symbols as key type to prevent SQL injection until we add table column quoting.
Thanks @huuhait for initial work in #317. 
* add `#where` accepting `Hash(Symbol, _)`
* add `Criteria#equal` and `Criteria#not_equal` as original implementation of `Criteria#==` and `Criteria#!=`
* add `ExpressionBuilder` `#and`, `#or` and `#xor` methods that accepts array of conditions
**Model**
* add `Resource.where` accepting `Hash(Symbol, _)`
=> Add query.where accepting hash

scripts/migrations/20170119011460000_remove_enum_value.cr, scripts/migrations/20180312114638349_create_users.cr, spec/migration/table_builder/change_table_spec.cr, src/jennifer/migration/table_builder/change_table.cr, src/jennifer/migration/table_builder/drop_reference.cr
**Migration**
* fix `TableBuilder::ChangeTable#drop_reference` dropping column before reference
* add `TableBuilder::DropReference`
=> Fix #drop_reference

spec/migration/table_builder/change_table_spec.cr, src/jennifer/migration/table_builder/change_table.cr
Fix for [this issue](https://github.com/imdrasil/jennifer_sqlite3_adapter/issues/35).  
**Migration**
* `TableBuilder::ChangeTable` now performs `DropForeignKey`, `DropIndex` & `DropReference` before any column manipulation
=> Fix change_table command executing order

docs/crud.md, docs/eager_loading.md, docs/query_dsl.md, spec/query_builder/executables_spec.cr, src/jennifer/adapter/base_sql_generator.cr, src/jennifer/query_builder/criteria.cr, src/jennifer/query_builder/executables.cr
Extend `Query#pluck` so it is possible to select only desired attributes from a database without a need to cast values later in the code.
* `#pluck` accepts splatted named tuple of desired attribute-type pairs and returns array of such tuples as a records 
* `.select_clause`  uses specified query attributes to select and fall back to custom fields only if there is no custom attribute to select
=> Extend #pluck to accept splatted named tuple

spec/model/timestamp_spec.cr, src/jennifer/model/timestamp.cr
**Model**
* `updated_at` and `created_at` fields aren't override on save if have been set manually
=> Allow to set custom values for created_at and updated_at

docs/configuration.md, spec/adapter/base_spec.cr, spec/config_spec.cr, src/jennifer/adapter/base.cr, src/jennifer/config.cr
Add ssl related crystal-pg config options: `auth_methods`, `sslmode`, `sslcert`, `sslkey`, `sslrootcert`
Postgres compatible databases hosted by Azure and CockroachLabs require `cleartext` auth method with ssl verification, but crystal-pg by default does not allow `cleartext`.
One needs to override accepted auth methods with option `auth_methods`.
When `cleartext` auth is used, it's better to fully verify the server's certificate, thus adding several ssl related options.
See related crystal-pg issues:
[#237](https://github.com/will/crystal-pg/issues/237)
[#192](https://github.com/will/crystal-pg/issues/192)
[#220](https://github.com/will/crystal-pg/pull/220)
**Config**
Add `crystal-pg` connection config options `auth_methods`, `sslmode`, `sslcert`, `sslkey`, `sslrootcert`.
=> Add ssl related crystal-pg config options: `auth_methods`, `sslmode`, `sslcert`, `sslkey`, `sslrootcert`

src/jennifer/adapter/mysql/command_interface.cr
Add the --port argument to mysql command in order to correctly execute the `sam.cr db:schema:load`
In case the DB is not hosted on the default MySQL port (3306)
=> Add missing port arg. into load_schema cmd

docs/getting_started.md
Small documentation fix to the `database.yml` example on the getting started guide.
=> Fix environment suffix in example database.yml

.github/workflows/ci.yml, Makefile, docs/model_mapping.md, scripts/migrations/20181017202211501_create_column_alias_models.cr, spec/adapter/base_spec.cr, spec/adapter/mysql/sql_generator_spec.cr, spec/adapter/postgres/sql_generator_spec.cr, spec/config_spec.cr, spec/model/authentication_spec.cr, spec/model/base_spec.cr, spec/model/mapping_spec.cr, spec/model/sti_mapping_spec.cr, spec/models.cr, spec/view/base_spec.cr, spec/view/mapping_spec.cr, spec/view/materialized_spec.cr, spec/view/translation_spec.cr, src/jennifer/adapter/mysql/schema_processor.cr, src/jennifer/adapter/postgres/schema_processor.cr, src/jennifer/migration/table_builder/change_table.cr, src/jennifer/migration/table_builder/create_table.cr, src/jennifer/model/base.cr, src/jennifer/model/mapping.cr, src/jennifer/model/optimistic_locking.cr, src/jennifer/model/sti_mapping.cr, src/jennifer/query_builder/query.cr, src/jennifer/view/base.cr
**Model**
* rename `#changes` to `#changes_before_typecast`
* add `:generated` option to mapping
* add generated column support for mysql and postgres adapters
**Migration**
* add `TableBuilder::CreateTable#generated` method to define generated column
=> Add generated column support

docs/pagination_and_ordering.md, src/jennifer/adapter/base.cr, src/jennifer/model/base.cr, src/jennifer/query_builder/aggregations.cr, src/jennifer/query_builder/executables.cr, src/jennifer/query_builder/query.cr
Change Query.count to return `Int64` instead of `Int32`
Change Query.offset to accept `Int32` or `Int64` as input instead of only `Int32`
https://github.com/imdrasil/jennifer.cr/issues/399
**Breaking change**: Query.count returns `Int64` instead of `Int32`
**Breaking change**: Query.offset accepts `Int32` or `Int64` as input instead of only `Int32`
**Model**
**Breaking change**: Model.count returns `Int64` instead of `Int32`
=> Count returns Int64 and offset accepts Int32 or Int64

.github/workflows/ci.yml, src/jennifer/adapter/postgres.cr, src/jennifer/adapter/postgres/numeric.cr, src/jennifer/model/common_mapping.cr, src/jennifer/model/sti_mapping.cr, src/jennifer/model/translation.cr, src/jennifer/query_builder/function.cr, src/jennifer/query_builder/order_expression.cr, src/jennifer/query_builder/statement.cr, src/jennifer/query_builder/values.cr, src/jennifer/relation/i_relation.cr, src/jennifer/relation/many_to_many.cr, src/jennifer/relation/polymorphic_belongs_to.cr, src/jennifer/relation/relation_stub.cr
Addresses warnings from the crystal 1.5.0
Fix #412 
**General**
* address "positional parameter of the overridden method, which has a different name and may affect named argument passing" crystal `1.5.0` warning (for full list see [MR](https://github.com/imdrasil/jennifer.cr/pull/413))
=> Rename override methods arguments to be consistent with original name

spec/model/authentication_spec.cr, src/jennifer/model/authentication.cr
Fix #419
**Model**
* fix a bug when password digest wasn't generated when password was set by passing it to a constructor
=> Set password digest when password was given to constructor

src/jennifer/generators/field.cr
Address #417 
**General**
* add `jsonb` type support for model and migration generators
=> Add jsonb type support for model/migration generator

.github/workflows/ci.yml, shard.yml, spec/model/sti_mapping_spec.cr, spec/models.cr, spec/query_builder/eager_loading_spec.cr, src/jennifer/adapter/base.cr, src/jennifer/model/callback.cr, src/jennifer/model/common_mapping.cr, src/jennifer/model/mapping.cr, src/jennifer/model/sti_mapping.cr, src/jennifer/model/timestamp.cr
Besides fixing STI model initializing using hash constructor this PR also adds extra layer of database column value coercing. This means that when a result set is read as a hash based on the received data types specification from the database model adapter is used to coerce them based on the attribute desired type.
Fix #403 
**Model**
* add missing STI initialization to constructors accepting a hash or named tuple
* use `Adapter::Base.coerce_database_value` in constructors accepting a hash or named tuple to coerce values for columns that don't have specified converter 
**Adapter**
* add `Base.coerce_database_value` method to provide interface to perform coercing from default database type used to read column to hash to a desired model attribute type
=> Add STI support to hash-based model initializer

docs/getting_started.md
Hi!
Without fix it throws an error on fresh projects, like:
```
In config/initializers/database.cr:9:15
9 | conf.logger.level = APP_ENV == "development" ? :debug : :error
^----
Error: no overload matches 'Log#level=' with type Symbol
Overloads are:
- Log#level=(value : Severity)
```
```yaml
jennifer:
git: https://github.com/imdrasil/jennifer.cr.git
version: 0.12.0
```
```bash
$ amber --version
Amber CLI (amberframework.org) - v1.2.2
$ crystal --version
Crystal 1.5.0 (2022-07-06)
LLVM: 14.0.6
Default target: x86_64-apple-macosx
$ shards --version
Shards 0.17.0 (2022-03-24)
```
Actualize documentation for crystal version 1.5 to avoid "no overload matches" error
=> Docs: fix logger level configuration

spec/adapter/base_spec.cr, src/jennifer/adapter/base.cr
Allows Adapter::Base#connection_string to render a connection string such as postgres://localhost/db_name
previously, when given no username or password, it would render postgres://@localhost/db_name, which is an invalid connection string.
Re my issues getting started at #444 -- the first thing I tried to do was to connect to my local database without a username or password.
I ran into this with posgresql, but I did not have a local mysql installation available for testing.
**Config**
[BUGFIX] Now connection strings can be rendered without username or password.
=> Render a proper connection string without username or password

.github/run_integration_tests.sh, .github/setup_mysql.sh, .github/shard.override.yml, .github/shard_micrate.yml, .github/shard_simple.yml, .github/workflows/ci.yml, README.md, docs/command_line.md, docs/configuration.md, docs/getting_started.md, docs/migration.md, scripts/run.cr, shard.override.yml, shard.yml, spec/adapter/db_colorized_formatter_spec.cr, spec/adapter/db_formatter_spec.cr, spec/adapter/result_parsers_spec.cr, spec/integration/sam/blank_application.cr, spec/integration/spec_helper.cr, spec/spec_helper.cr, spec/support/config.cr, src/jennifer/adapter/db_colorized_formatter.cr, src/jennifer/adapter/db_formatter.cr, src/jennifer/config.cr, src/jennifer/migration/runner.cr
Fix #446 - Instead of accepting custom `Log` instance with specified logging level Jennifer should rely on bound log settings
**General**
* use `0.16.0` of `crystal-lang/crystal-mysql` in tests
* use `0.28.0` of `will/crystal-pg` in tests
* stop supporting crystal `0.36.0`
**Adapter**
* add colorized log formatter `Jennifer::Adapter::DBColorizedFormatter`
**Config**
* change default value of `.logger` to `Log.for("db")` so it it possible to set log level using `Log.setup`; discourage using `config.logger=`
**Migration**
* display a warning message during migration if there is no migration class is loaded but migrations location has crystal files
=> Rely on global log level setup instead of waiting for custom logger to be assigned

spec/generators/migration_spec.cr, spec/generators/model_spec.cr, spec/integration/sam_test.cr, spec/integration/shared_helpers.cr, spec/integration/spec_helper.cr, src/jennifer/generators/base.cr, src/jennifer/model/base.cr, src/jennifer/sam.cr, src/jennifer/view/base.cr
Decouples Jennifer's generators from Sam implementation so it should be easier to use it standalone. This should not affect any common user flow.
Thank you @charles-liang for the initial implementation :pray: 
**General**
* `Jennifer::Generators::Base#args` is now `Array(Float64 | Int32 | String)` instead of `Sam::Args`
**Model**
* rename argument `pull` of `Base.build` to `values` 
**View**
* rename argument `pull` of `Base.build` to `values`
=> Decouple generator arguments from Sam
